version: '3'

services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_USER: 'bhumit070'
      POSTGRES_PASSWORD: 'bhumit070'
      PGDATA: /data/postgres
    ports:
      - '5001:5432'
    restart: unless-stopped

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'bhoomit@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'bhumit070'
    ports:
      - '5000:80'
